name: Markdown Check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  markdown-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List Markdown files
        run: find . -name '*.md' -not -path './.git/*' -print | sort
